### ISSUE TITLE
name 'ParameterMapping' is not defined

### ISSUE THREAD

**Issue by paulflang** [ICB-DCM/pyPESTO#314] opened 2020-05-07 18:56 UTC
I am just trying to reproduce the AMICI Python example "Boehm" from the documentation. However, in cell 14:
```
model.requireSensitivitiesForAllParameters()
solver.setSensitivityMethod(amici.SensitivityMethod_forward)
solver.setSensitivityOrder(amici.SensitivityOrder_first)
objective = pypesto.AmiciObjective(model, solver, [edata], 1)
```
I get the following error:
```
NameError                                 Traceback (most recent call last)
<ipython-input-26-8453b4d05827> in <module>()
      6 
      7 
----> 8 objective = pypesto.AmiciObjective(model, solver, [edata], 1)

/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/pypesto/objective/amici_objective.py in __init__(self, amici_model, amici_solver, edatas, max_sensi_order, x_ids, x_names, parameter_mapping, guess_steadystate, n_threads, amici_object_builder, calculator)
    163             # use identity mapping for each condition
    164             parameter_mapping = create_identity_parameter_mapping(
--> 165                 amici_model, len(edatas))
    166         self.parameter_mapping = parameter_mapping
    167 

/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/pypesto/objective/amici_util.py in create_identity_parameter_mapping(amici_model, n_conditions)
     98     x_ids = list(amici_model.getParameterIds())
     99     x_scales = list(amici_model.getParameterScale())
--> 100     parameter_mapping = ParameterMapping()
    101     for _ in range(n_conditions):
    102         condition_map_sim_var = {x_id: x_id for x_id in x_ids}

NameError: name 'ParameterMapping' is not defined
```

**Comment by yannikschaelte** [comment] 2020-05-07 19:52
Hi @paulflang . `ParameterMapping` is defined in `amici.parameter_mapping` which was introduced in amici v0.10.21. Might your AMICI version be older?

**Comment by paulflang** [comment] 2020-05-07 19:55
I just pip installed it today and it should be the right version:
```
In [27]: amici.__version__
Out[27]: '0.10.21'
```

**Comment by FFroehlich** [comment] 2020-05-07 19:58
> I just pip installed it today and it should be the right version:
> 
> ```
> In [27]: amici.__version__
> Out[27]: '0.10.21'
> ```

Make sure the notebook is using the kernel from the right virtual environment where the latest version of amici is installed (see https://ipython.readthedocs.io/en/stable/install/kernel_install.html)

**Comment by yannikschaelte** [comment] 2020-05-07 20:00
E.g. `which jupyter` should point to the pip/conda environment where the latest amici+pypesto are installed.

**Comment by paulflang** [comment] 2020-05-07 20:11
I am using ipython from the ubuntu CLI.
`which ipython` returns `/usr/bin/ipython`, but I do not see `pyPesto` or `amici` directories or files there.

I am just a bit confused: why would `amici.__version__`, if called from inside ipython, return a version from a different virtual environment than the one it is called from?

**Comment by yannikschaelte** [comment] 2020-05-07 20:16
IPython may not have been installed in the virtual environment. Thus, when you invoke jupyter, implicitly the next available one is called, which may however be from a different python environment. You can check the context of your ipython environment by e.g. executing `!which python3` in a notebook cell.

To fix this, proceed as in the above link, usually `pip install ipython jupyter` (where pip is from the virtual environment) should do the trick.

**Comment by FFroehlich** [comment] 2020-05-07 20:17
> IPython may not have been installed in the virtual environment. Thus, when you invoke jupyter, implicitly the next available one is called, which may however be from a different python environment. You can check the context of your ipython environment by e.g. executing `!which python3` in a notebook cell.
> 
> To fix this, proceed as in the above link, usually `pip install ipython jupyter` (where pip is from the virtual environment) should do the trick.

You can also start jupyter/ipython from outside the virtual env and just select a different kernel for execution: https://doc.cocalc.com/howto/jupyter-kernel-selection.html

**Comment by paulflang** [comment] 2020-05-07 20:25
@FFroehlich : Thanks for the clarification.

@yannikschaelte : `!which python` returns `/usr/bin/python3` and I do not see pyPesto or amici directories in `/usr/bin/`.

But I am not using a jupyter notebook. I am running ipython from the Ubuntu terminal. Is there an alternative to `pip install ipython jupyter`?

**Comment by yannikschaelte** [comment] 2020-05-07 20:30
> @yannikschaelte : `!which python` returns `/usr/bin/python3` and I do not see pyPesto or amici directories in `/usr/bin/`.

Sorry, I did not mean they should be virtually in the same folder, just the python used in ipython should be the same for which you installed pypesto+amici. To start with, you do use a virtual environment, right? I.e. when you do `which python3` in the command line, it is not /usr/bin/python3.

> 
> But I am not using a jupyter notebook. I am running ipython from the Ubuntu terminal. Is there an alternative to `pip install ipython jupyter`?

When you don't use jupyter, just installing ipython or ipykernel will suffice as in the above link, or pick a different kernel as pointed out by Fabi (if possible from the CLI, not sure).

**Comment by paulflang** [comment] 2020-05-07 20:49
No, I am not not using a virtual environment:
```
paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ which python3
/usr/bin/python3
paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ ipython
Python 3.6.9 (default, Apr 18 2020, 01:56:04) 
Type 'copyright', 'credits' or 'license' for more information
IPython 7.14.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: !which python3                                                                                   
/usr/bin/python3

In [2]: !which ipython                                                                                   
/home/paul/.local/bin/ipython

In [3]: exit()                                                                                           
paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ which ipython
/home/paul/.local/bin/ipython
paul@paul-VirtualBox:/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ 
```

**Comment by yannikschaelte** [comment] 2020-05-07 21:11
Ok, so in the relevant ipython environment when you call amici you have `amici.__version__` 0.10.21, right? Can you try converting the notebook to script (e.g. via `jupyter nbconvert --to script THE_NOTEBOOK.ipynb` and then calling via `python3 THE_NOTEBOOK.py` whether the error persists?

With the latest amici version 0.10.21 and latest pypesto 0.0.13, I am not able to reproduce the error, so I suspect there must still be something wrong on your system ...

**Comment by paulflang** [comment] 2020-05-07 21:34
> Ok, so in the relevant ipython environment when you call amici you have amici.__version__ 0.10.21, right?

correct.

> Can you try converting the notebook to script (e.g. via jupyter nbconvert --to script THE_NOTEBOOK.ipynb and then calling via python3 THE_NOTEBOOK.py whether the error persists?

Unfortunately, the error persists.

If you cannot reproduce the error, I think I'll try to get my python installations sorted and reinstall amici and pypesto. Thank you very much for your support so far.

**Comment by paulflang** [comment] 2020-05-09 23:56
I created a new Ubuntu VM and tried to reinstall pyPESTO and AMICI. Unfortunately, I could not get it done.
I decided to built a Docker container from the pyPESTO Docker image. I was able to reproduce the AMICI Python example "Boehm" from inside the container.

**Comment by dweindl** [comment] 2020-05-10 07:24
> Unfortunately, I could not get it done.

What happened?

>  I decided to built a Docker container from the pyPESTO Docker image. I was able to reproduce the AMICI Python example "Boehm" from inside the container.

:+1:

**Comment by paulflang** [comment] 2020-05-10 09:03
> What happened

```
error: command 'swig' failed with exit status 1
```
To double check if I have swig installed:
```
(std) paul@paul-VirtualBox:~/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ sudo apt-get update -y
[sudo] password for paul: 
Hit:1 http://at.archive.ubuntu.com/ubuntu focal InRelease                                               
Hit:2 http://security.ubuntu.com/ubuntu focal-security InRelease                                        
Hit:3 http://at.archive.ubuntu.com/ubuntu focal-updates InRelease
Hit:4 http://at.archive.ubuntu.com/ubuntu focal-backports InRelease
Reading package lists... Done
(std) paul@paul-VirtualBox:~/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ sudo apt-get install -y swig
Reading package lists... Done
Building dependency tree       
Reading state information... Done
swig is already the newest version (4.0.1-5build1).
0 upgraded, 0 newly installed, 0 to remove and 23 not upgraded.
```
I copied in the code from the example to the file `boehm_JProteomeRes2014.py` and ran:
```
(std) paul@paul-VirtualBox:~/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ python3 boehm_JProteomeRes2014.py
/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example/boehm_JProteomeRes2014/boehm_JProteomeRes2014.xml
Species:  ['STAT5A', 'STAT5B', 'pApB', 'pApA', 'pBpB', 'nucpApA', 'nucpApB', 'nucpBpB']

Reactions:
v1_v_0:   2 STAT5A  ->      pApA		[cyt * BaF3_Epo * STAT5A^2 * k_phos]
v2_v_1:  STAT5A +  STAT5B  ->      pApB		[cyt * BaF3_Epo * STAT5A * STAT5B * k_phos]
v3_v_2:   2 STAT5B  ->      pBpB		[cyt * BaF3_Epo * STAT5B^2 * k_phos]
v4_v_3:       pApA  ->   nucpApA		[cyt * k_imp_homo * pApA]
v5_v_4:       pApB  ->   nucpApB		[cyt * k_imp_hetero * pApB]
v6_v_5:       pBpB  ->   nucpBpB		[cyt * k_imp_homo * pBpB]
v7_v_6:    nucpApA  ->  2 STAT5A		[nuc * k_exp_homo * nucpApA]
v8_v_7:    nucpApB  -> STAT5A +  STAT5B		[nuc * k_exp_hetero * nucpApB]
v9_v_8:    nucpBpB  ->  2 STAT5B		[nuc * k_exp_homo * nucpBpB]
Observables: {'observable_pSTAT5A_rel': {'name': '', 'formula': '(100 * pApB + 200 * pApA * specC17) / (pApB + STAT5A * specC17 + 2 * pApA * specC17)'}, 'observable_pSTAT5B_rel': {'name': '', 'formula': '-(100 * pApB - 200 * pBpB * (specC17 - 1)) / (STAT5B * (specC17 - 1) - pApB + 2 * pBpB * (specC17 - 1))'}, 'observable_rSTAT5A_rel': {'name': '', 'formula': '(100 * pApB + 100 * STAT5A * specC17 + 200 * pApA * specC17) / (2 * pApB + STAT5A * specC17 + 2 * pApA * specC17 - STAT5B * (specC17 - 1) - 2 * pBpB * (specC17 - 1))'}}
{'observable_pSTAT5A_rel': 'sd_pSTAT5A_rel', 'observable_pSTAT5B_rel': 'sd_pSTAT5B_rel', 'observable_rSTAT5A_rel': 'sd_rSTAT5A_rel'}
error: command 'swig' failed with exit status 1

Traceback (most recent call last):
  File "boehm_JProteomeRes2014.py", line 71, in <module>
    sbml_importer.sbml2amici(model_name,
  File "/home/paul/venvs/std/lib/python3.8/site-packages/amici/sbml_import.py", line 307, in sbml2amici
    exporter.compile_model()
  File "/home/paul/venvs/std/lib/python3.8/site-packages/amici/logging.py", line 179, in wrapper_timer
    rval = func(*args, **kwargs)
  File "/home/paul/venvs/std/lib/python3.8/site-packages/amici/ode_export.py", line 1909, in compile_model
    self._compile_c_code(compiler=self.compiler,
  File "/home/paul/venvs/std/lib/python3.8/site-packages/amici/ode_export.py", line 1979, in _compile_c_code
    result = subprocess.run(script_args,
  File "/usr/lib/python3.8/subprocess.py", line 512, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/home/paul/venvs/std/bin/python3', '/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example/tmp/boehm_JProteomeRes2014/setup.py', '--quiet', 'build_ext', '--build-lib=/media/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example/tmp/boehm_JProteomeRes2014']' returned non-zero exit status 1.
(std) paul@paul-VirtualBox:~/sf_DPhil_Project/Project07_Parameter Fitting/pyPESTO/doc/example$ 
```

**Comment by dweindl** [comment] 2020-05-10 10:31
Ah, I see. This is related to finding the correct swig executable and should be fixed in the upcoming AMICI release, in case you prefer that over docker usage.

**Comment by yannikschaelte** [comment] 2020-05-31 21:03
closing as this seems resolved. re-open if something is still unclear :)

**Closed by yannikschaelte** 2020-05-31 21:03 UTC

**Comment by harshitaojha** [comment] 2021-06-29 13:42
I too was getting the same error of ParameterFitting() and on installation of correct amici and pypesto versions I did not get the same error instead my notebook was crashing everytime. I checked the env where amici and pypesto were installed and it was python3.7/dist-packages. Any suggestions on how may I get this sorted?
